title: "Title"
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Ask a clear question
        Please provide as much detail as possible so others can help you effectively.

  - type: textarea
    id: problem
    attributes:
      label: What is the problem?
      description: Describe the behavior you're seeing, what you expected, and why it's an issue.
      placeholder: |
        I'm seeing [describe issue] when I try to [action]...
    validations:
      required: true

  - type: textarea
    id: expected-outcome
    attributes:
      label: What is the expected outcome?
      description: Describe what you expected to happen instead of the current behavior.
      placeholder: |
        I expected [this outcome] when I [performed this action]...
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: What is the error message?
      description: Paste the full error message or stack trace.
      render: shell

  - type: textarea
    id: view-code
    attributes:
      label: Code of the view 
      description: Share the relevant portion of your view or template code.
      render: javascript

  - type: textarea
    id: query-code
    attributes:
      label: Code of the query
      description: Share the relevant portion of your query code.
      render: python

  - type: textarea
    id: attempts
    attributes:
      label: What have you tried?
      description: Describe what you've already done to solve the problem.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Before posting
      options:
        - label: I have searched existing discussions and issues
          required: true
        - label: I included all relevant code and error messages
          required: true
        - label: This is not a duplicate of another open thread
          required: true
